language: clojure
services:
  - postgresql
before_script:
  - psql -c "CREATE ROLE nhtest WITH CREATEDB LOGIN PASSWORD 'nhtest';" -U postgres
  - psql -c "CREATE DATABASE nhtestdb WITH OWNER nhtest ENCODING 'UTF-8';" -U postgres
  